### ISSUE TITLE
changing image or editor position.

### ISSUE THREAD

**Issue by Thanooss** [RexanWONG/text-behind-image#11]
In Desktop Image is not visible to the  user while setting rotation, font weight and text opacity. user need to set the settings first and then scroll up and see the changes which is not feasible especially while rotation text.
![Screenshot (40)](https://github.com/user-attachments/assets/e5d0d69c-4c88-44f6
![Screenshot (40)](https://github.com/user-attachments/assets/7a891fa8-e2c1-4d49-a9cd-82f1955e0ce6)
-b91b-a4d7f551b25e)

**Comment by KrishnaCodez** [comment]
Hi @DanonymousCoder! 👋

I’ve rebuild this product with an enhanced UI/UX experience, aiming for a smoother and more intuitive interface. I’ll also be adding new features in the coming days, so stay tuned!

Feel free to check it out here: [Website Link](https://www.magictext.tech/)

If you’d like to contribute or explore the code,  visit the: [GitHub repo](https://github.com/KrishnaCodez/MagicText)

Looking forward to your feedback ❤️.

**Comment by KrishnaCodez** [comment]
Hi @Thanooss! 👋

I’ve rebuild this product with an enhanced UI/UX experience, aiming for a smoother and more intuitive interface. I’ll also be adding new features in the coming days, so stay tuned!

Feel free to check it out here: [Website Link](https://www.magictext.tech/)

If you’d like to contribute or explore the code,  visit the: [GitHub repo](https://github.com/KrishnaCodez/MagicText)

Looking forward to your feedback ❤️.

**Comment by RexanWONG** [comment]
thanks for bringing it up, this issue has now been solved. there's a scrollbar now.
