### ISSUE TITLE
What is environment variables for this

### ISSUE THREAD

**Issue by CpenAI** [RexanWONG/text-behind-image#4]
I open your repository in vercel and I can't find environment variables to set in this. What values I set to use this app.

**Comment by Amanbajrur** [comment]
![IMG_20241009_080959](https://github.com/user-attachments/assets/d31e6afd-9527-43bd-ade8-fb76b0a58319)
Cam you help me what values I set here to deploy your app.

**Comment by RexanWONG** [comment]
Supabase values - thats only for making authentication work with the app.

Populate the .env with 
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY

**Comment by CpenAI** [comment]
Thanks

**Comment by CpenAI** [comment]
Everything fine
